Zadanie 9

Wczytaj cały dataset Iris (4 cechy). Zaimplementuj standaryzację (mean=0, std=1) dla każdej cechy używając operacji NumPy. Porównaj wynik z StandardScaler z sklearn.

Dataset:
- Iris (sklearn.datasets.load_iris)

Wymagania:
- Oblicz mean i std per kolumna ( axis=0 )
- Zastosuj wzór: (X - mean) / std
- Sprawdź mean i std po standaryzacji
- Porównaj z sklearn.preprocessing.StandardScaler
- Oblicz max różnicę między implementacjami

Oczekiwany rezultat:
- Macierz X_standardized (150, 4)
- Weryfikacja: mean≈0, std≈1
- Max różnica vs sklearn

In [2]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.preprocessing import StandardScaler

# Wczytanie danych
iris = load_iris()
X = iris.data

print("Pierwotne dane (5 pierwszych):")
print(X[:5])
print(f"\nKształt: {X.shape}")

# Standaryzacja: (X - mean) / std (dla każdej kolumny)
mean = X.mean(axis=0)   # Średnia per cecha (4 wartości)
std = X.std(axis=0)     # Odchylenie standardowe per cecha (4 wartości)

print(f"\nŚrednia per cecha: {mean}")
print(f"Std per cecha: {std}")

# Broadcasting: (150, 4) - (4, ) = (150, 4)
X_standardized = (X - mean) / std

print("\nZstandaryzowane dane (5 pierwszych):")
print(X_standardized[:5])
print(f"\nKształt: {X_standardized.shape}")

mean_standardized = X_standardized.mean(axis=0)
std_standardized = X_standardized.std(axis=0)

# Weryfikacja: średnia = 0, std = 1
print(f"\nPo standaryzacji:")
print(f"  Średnia per cecha: {mean_standardized}")
print(f"  Std per cecha: {std_standardized}")

# Porównanie z sklearn
scaler = StandardScaler()
X_sklearn = scaler.fit_transform(X)

max_difference = np.abs(X_standardized - X_sklearn).max()
print("\nMax różnica między zaimplementowaną standaryzacją, a uzyskaną z użyciem StandardScaler z sklearn: ")
print(f"  Max różnica: {max_difference:.10f}")


Pierwotne dane (5 pierwszych):
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Kształt: (150, 4)

Średnia per cecha: [5.84333333 3.05733333 3.758      1.19933333]
Std per cecha: [0.82530129 0.43441097 1.75940407 0.75969263]

Zstandaryzowane dane (5 pierwszych):
[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]

Kształt: (150, 4)

Po standaryzacji:
  Średnia per cecha: [-1.69031455e-15 -1.84297022e-15 -1.69864123e-15 -1.40924309e-15]
  Std per cecha: [1. 1. 1. 1.]

Max różnica między zaimplementowaną standaryzacją, a uzyskaną z użyciem StandardScaler z sklearn: 
  Max różnica: 0.0000000000
