Zadanie 4

Utwórz tablicę 2D (5x4) wypełnioną losowymi liczbami całkowitymi od 1 do 50.

Wymagania:
- Użyj np.random.randint()
- Wypisz shape tablicy
- Wypisz drugi wiersz
- Wypisz trzecią kolumnę
- Wypisz element z pozycji (2, 3)

In [15]:
import numpy as np

tablica_2d = np.random.randint(1, 50, size=(5, 4))

print("Tablica 2D: \n")
print(tablica_2d)
print()
print("Shape tablicy:", tablica_2d.shape)
print("Drugi wiersz:", tablica_2d[1])
print("Trzecia kolumna:", tablica_2d[:, 2])
print("Element z pozycji (2, 3):", tablica_2d[2, 3])

Tablica 2D: 

[[35 45 48 31]
 [ 6 25 14  1]
 [30 46 28  3]
 [28 39  5  8]
 [40 25  9  1]]

Shape tablicy: (5, 4)
Drugi wiersz: [ 6 25 14  1]
Trzecia kolumna: [48 14 28  5  9]
Element z pozycji (2, 3): 3
