Zadanie 10

Dana tablica ocen (5 studentów x 4 egzaminy):

exams = np.array([
    [78, 85, 92, 88],
    [65, 72, 68, 70],
    [90, 88, 95, 92],
    [55, 60, 58, 62],
    [82, 79, 85, 80]
])

Dodaj bonus do każdego egzaminu: [5, 10, 5, 10]

Następnie pomnóż wyniki każdego studenta przez mnożnik: [1.0, 1.1, 0.95, 1.15, 1.0]

Wymagania:
- Użyj broadcastingu (bez pętli)
- Wypisz wyniki przed i po

In [7]:
import numpy as np

exams = np.array([
    [78, 85, 92, 88],
    [65, 72, 68, 70],
    [90, 88, 95, 92],
    [55, 60, 58, 62],
    [82, 79, 85, 80]
])

print("Tablica ocen (5 studentów x 4 egzaminy):")
print(exams)

bonusy_do_egzaminow = np.array([5, 10, 5, 10])
print("\nBonusy do każdego wyniku z egzaminu:", bonusy_do_egzaminow)

# dodatnie bonusu do każdego egzaminu
egzaminy_z_bonusem = exams + bonusy_do_egzaminow
print("\nTablica wyników studenta z bonusami:")
print(egzaminy_z_bonusem)

mnozniki = np.array([1.0, 1.1, 0.95, 1.15, 1.0]).reshape(5, 1)
print("\nMnożniki wyników z egzaminów studenta:")
print(mnozniki)

# pomnożone wyniki każdego studenta przez mnożnik
skorygowane_wyniki_egzaminow = egzaminy_z_bonusem * mnozniki
print("\nWyniki egzaminów po bonusach i mnożnikach:")
print(skorygowane_wyniki_egzaminow)



Tablica ocen (5 studentów x 4 egzaminy):
[[78 85 92 88]
 [65 72 68 70]
 [90 88 95 92]
 [55 60 58 62]
 [82 79 85 80]]

Bonusy do każdego wyniku z egzaminu: [ 5 10  5 10]

Tablica wyników studenta z bonusami:
[[ 83  95  97  98]
 [ 70  82  73  80]
 [ 95  98 100 102]
 [ 60  70  63  72]
 [ 87  89  90  90]]

Mnożniki wyników z egzaminów studenta:
[[1.  ]
 [1.1 ]
 [0.95]
 [1.15]
 [1.  ]]

Wyniki egzaminów po bonusach i mnożnikach:
[[83.   95.   97.   98.  ]
 [77.   90.2  80.3  88.  ]
 [90.25 93.1  95.   96.9 ]
 [69.   80.5  72.45 82.8 ]
 [87.   89.   90.   90.  ]]
