Zadanie 8

Dana tablica:

arr = np.arange(1, 13)

Wykonaj:
- Zmień kształt na (3, 4)
- Zmień kształt na (2, 6)
- Zmień kształt na (4, 3)
- Spłaszcz z powrotem do 1D (flatten lub ravel)

Wymagania:
- Użyj metody .reshape()
- Sprawdź różnicę między flatten() a ravel()

In [15]:
import numpy as np

arr = np.arange(1, 13)

print("Tablica:")
print(arr)

arr = arr.reshape(3, 4)
print("\nZmiana kształtu na (3, 4):\n", arr)

arr = arr.reshape(2, 6)
print("\nZmiana kształtu na (2, 6):\n", arr)

arr = arr.reshape(4, 3)
print("\nZmiana kształtu na (4, 3):\n", arr)

arr_new = arr.flatten()
arr_new[0] = 10 # zmiana wartości elementu 0 tablicy w celu sprawdzenia czy działa się na kopii tablicy czy na view - oryginale
print("\nSpłaszczono z powrotem do 1D (metoda flatten()):\n")
print("Oryginalna tablica:\n", arr)
print("\nNowa tablica:\n", arr_new)
print("Metoda flatten() zwróciła kopię tablicy. arr_new[0] = 10 spowodowało tylko" \
" zmianę wartości arr_new[0]. Wartość w arr[0] pozostała nie naruszona.")

arr_new = arr.ravel()
arr_new[0] = 10 # zmiana wartości elementu 0 tablicy w celu sprawdzenia czy działa się na kopii tablicy czy na view - oryginale
print("\nSpłaszczono z powrotem do 1D (metoda ravel()):\n")
print("Oryginalna tablica:\n", arr)
print("\nNowa tablica:\n", arr_new)
print("Metoda ravel() zwróciła view. Zmiana wartości arr_new[0] = 10 " \
"spowodowała zmianę wartości arr[0], a nie jedynie wartości w arr_new[0].")

# metoda flatten() zwraca nową kopię tablicy, natomiast
# metoda ravel() próbuje zwrócić view oryginalnej tablicy

Tablica:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Zmiana kształtu na (3, 4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Zmiana kształtu na (2, 6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

Zmiana kształtu na (4, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Spłaszczono z powrotem do 1D (metoda flatten()):

Oryginalna tablica:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Nowa tablica:
 [10  2  3  4  5  6  7  8  9 10 11 12]
Metoda flatten() zwróciła kopię tablicy. arr_new[0] = 10 spowodowało tylko zmianę wartości arr_new[0]. Wartość w arr[0] pozostała nie naruszona.

Spłaszczono z powrotem do 1D (metoda ravel()):

Oryginalna tablica:
 [[10  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Nowa tablica:
 [10  2  3  4  5  6  7  8  9 10 11 12]
Metoda ravel() zwróciła view. Zmiana wartości arr_new[0] = 10 spowodowała zmianę wartości arr[0], a nie jedynie wartości w arr_new[0].
