Zadanie 7

Utwórz następujące macierze:
- Macierz 3x3 wypełnioną zerami
- Macierz 4x4 wypełnioną jedynkami
- Macierz identyczności 5x5
- Macierz 3x4 wypełnioną liczbą 7
- Wektor 10 równoodległych wartości od 0 do 1

Wymagania:
- Użyj np.zeros , np.ones , np.eye , np.full , np.linspace

In [10]:
import numpy as np

print("Macierz 3x3 wypełniona zerami:")
macierz_zerowa = np.zeros((3, 3))
print(macierz_zerowa)

print("\nMacierz 4x4 wypełniona jedynkami:")
macierz_jedynek = np.ones((4, 4))
print(macierz_jedynek)

print("\nMacierz identyczności 5x5:")
macierz_identycznosci = np.eye(5)
print(macierz_identycznosci)

print("\nMacierz 3x4 wypełniona liczbą 7:")
pelna_macierz = np.full((3, 4), 7)
print(pelna_macierz)

print("\nWektor 10 równoodległych wartości od 0 do 1:")
przestrzen_liniowa = np.linspace(0, 1, 10)
print(przestrzen_liniowa)


Macierz 3x3 wypełniona zerami:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Macierz 4x4 wypełniona jedynkami:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Macierz identyczności 5x5:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Macierz 3x4 wypełniona liczbą 7:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Wektor 10 równoodległych wartości od 0 do 1:
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
