Zadanie 5

Dana tablica reprezentująca sprzedaż 4 produktów w 7 dni:

sales = np.random.randint(10, 100, size=(4, 7))

Oblicz i wypisz:
- Średnią sprzedaż per produkt (axis=1)
- Średnią sprzedaż per dzień (axis=0)
- Dzień z najwyższą sprzedażą (np.argmax)
- Produkt z najniższą średnią sprzedażą

In [8]:
import numpy as np

sales = np.random.randint(10, 100, size=(4, 7))

print("Sprzedaż 4 produktów w 7 dni:\n")
print(sales)
print()

print("\n--- Średnia sprzedaż per produkt ---")
produkt_means = np.mean(sales, axis=1)
for nr, srednia in enumerate(produkt_means):
    print(f"Produkt {nr+1}: {srednia:.1f}")

print("\n--- Średnia sprzedaż per dzień ---")
dzien_means = np.mean(sales, axis=0)
for dzien, srednia in enumerate(dzien_means):
    print(f"Dzień {dzien+1}: {srednia:.1f}")

dzien_najwyzsza_sprzedaza_indeks = np.argmax(dzien_means)
print(f"\nDzień z najwyższą sprzedażą:")
print(f"Dzień {dzien_najwyzsza_sprzedaza_indeks + 1} (średnia: {dzien_means[dzien_najwyzsza_sprzedaza_indeks]:.1f})")

produkt_najnizsza_srednia_sprzedaz_indeks = np.argmin(produkt_means)
print(f"\nProdukt z najniższą średnią sprzedażą:")
print(f"Produkt {produkt_najnizsza_srednia_sprzedaz_indeks + 1} (średnia: {produkt_means[produkt_najnizsza_srednia_sprzedaz_indeks]:.1f})")

Sprzedaż 4 produktów w 7 dni:

[[33 49 97 95 94 63 46]
 [57 76 94 97 92 37 68]
 [23 12 27 36 40 66 59]
 [64 39 33 28 34 68 98]]


--- Średnia sprzedaż per produkt ---
Produkt 1: 68.1
Produkt 2: 74.4
Produkt 3: 37.6
Produkt 4: 52.0

--- Średnia sprzedaż per dzień ---
Dzień 1: 44.2
Dzień 2: 44.0
Dzień 3: 62.8
Dzień 4: 64.0
Dzień 5: 65.0
Dzień 6: 58.5
Dzień 7: 67.8

Dzień z najwyższą sprzedażą:
Dzień 7 (średnia: 67.8)

Produkt z najniższą średnią sprzedażą:
Produkt 3 (średnia: 37.6)
